### ISSUE TITLE
Moron message

### ISSUE THREAD

**Issue by pacwoodson** [soerface/fb-unseen#2]
Hi,

I love your extension, and i felt ashamed when I saw your message after clicking "Okay" too fast. 
I run on many OSes with Chrome synchronized on each, and yes, I clicked too fast because I saw the message a coupe times already, and I read it, of course. 

This issue is not very important but I wanted to say to you that some good people like me can reach your violent but reasoned message :)

BTW, great job, I still do not understand why the "read" functionnality in facebook exists.

**Comment by soerface** [comment]
Hi,

thanks for your message. I guess I overreacted yesterday. The thing is, that, although I stated clearly my intents and that those ads can easily be disabled, there are so many people complaining and saying “oh my gosh what a shit now I have no other choice than removing it”. That made me a bit angry, because there is no reason anyone could not read my statement. I just didn’t thought about that there are good reasons for clicking it away fast. I have now changed it so that the button is just not there for five seconds. Maybe that will help, and that 5 seconds shouldn’t be too bad if using multiple computers.
